### ISSUE TITLE
index.html not included in package error while running the express example

### ISSUE THREAD

**Issue by codecpy** [vercel/pkg#1210]
# index.html not included in package error

The code example is found [here](https://github.com/vercel/pkg/tree/master/examples/express).
**When running it using the terminal, all is well**. I compiled it into an executable and there is where it keeps popping the same error again and again. I have already done like the example says on the [Readme.md](https://github.com/vercel/pkg/blob/master/examples/express/readme.md) but on running it gives out this error:

> john@john:~/Tofa/Projects/Convert node project into .exe/Secondtest/express$ ./express
> Error: File or directory '/**/express/views/index.html' was not included into executable at compilation stage. Please recompile adding it as asset or script.
    at error_ENOENT (pkg/prelude/bootstrap.js:539:17)
    at findNativeAddonForStat (pkg/prelude/bootstrap.js:1201:32)
    at statFromSnapshot (pkg/prelude/bootstrap.js:1224:25)
    at Object.stat (pkg/prelude/bootstrap.js:1250:5)
    at SendStream.sendFile (/snapshot/express/node_modules/send/index.js:721:6)
    at SendStream.pipe (/snapshot/express/node_modules/send/index.js:595:8)
    at sendfile (/snapshot/express/node_modules/express/lib/response.js:1103:8)
    at ServerResponse.sendFile (/snapshot/express/node_modules/express/lib/response.js:433:3)
    at /snapshot/express/index.js:21:9
    at Layer.handle [as handle_request] (/snapshot/express/node_modules/express/lib/router/layer.js:95:5)

## Code modification

I have tried modifying the code to include the file, but during the executable running, the same error is the output that I get.
Adding the scripts or the assets did not help.

My code now looks like this:

### Folder structure

.
├── node_modules
├── views
│   ├── lib
│        └── sakura.css
│   └── index.html
├── index.js
├── package.json
└── package-lock.json

### index.html

File contents are as follows:

```html
<html>

<head>
    <link rel="stylesheet" href="lib/sakura.css" type="text/css" />
</head>

<body>
    <h1>Hello, world!</h1>
    <br>
    <p>Its you again, Hello there!</p>
</body>

</html>
```

### sakura.css

```css
/* Sakura.css v1.0.0 *================* Minimal css theme. * Project: https: //github.com/oxalorg/sakura
*/


/* Body */

html {
    font-size: 62.5%;
    font-family: serif;
}

body {
    font-size: 1.8rem;
    line-height: 1.618;
    max-width: 38em;
    margin: auto;
    color: #4a4a4a;
    background-color: #f9f9f9;
    padding: 13px;
}

@media (max-width: 684px) {
    body {
        font-size: 1.53rem;
    }
}

@media (max-width: 382px) {
    body {
        font-size: 1.35rem;
    }
}

h1,
h2,
h3,
h4,
h5,
h6 {
    line-height: 1.1;
    font-family: Verdana, Geneva, sans-serif;
    font-weight: 700;
    overflow-wrap: break-word;
    word-wrap: break-word;
    -ms-word-break: break-all;
    word-break: break-word;
    -ms-hyphens: auto;
    -moz-hyphens: auto;
    -webkit-hyphens: auto;
    hyphens: auto;
}

h1 {
    font-size: 2.35em;
}

h2 {
    font-size: 2em;
}

h3 {
    font-size: 1.75em;
}

h4 {
    font-size: 1.5em;
}

h5 {
    font-size: 1.25em;
}

h6 {
    font-size: 1em;
}

small,
sub,
sup {
    font-size: 75%;
}

hr {
    border-color: #2c8898;
}

a {
    text-decoration: none;
    color: #2c8898;
}

a:hover {
    color: #982c61;
    border-bottom: 2px solid #4a4a4a;
}

ul {
    padding-left: 1.4em;
}

li {
    margin-bottom: 0.4em;
}

blockquote {
    font-style: italic;
    margin-left: 1.5em;
    padding-left: 1em;
    border-left: 3px solid #2c8898;
}

img {
    max-width: 100%;
}


/* Pre and Code */

pre {
    background-color: #f1f1f1;
    display: block;
    padding: 1em;
    overflow-x: auto;
}

code {
    font-size: 0.9em;
    padding: 0 0.5em;
    background-color: #f1f1f1;
    white-space: pre-wrap;
}

pre>code {
    padding: 0;
    background-color: transparent;
    white-space: pre;
}


/* Tables */

table {
    text-align: justify;
    width: 100%;
    border-collapse: collapse;
}

td,
th {
    padding: 0.5em;
    border-bottom: 1px solid #f1f1f1;
}


/* Buttons, forms and input */

input,
textarea {
    border: 1px solid #4a4a4a;
}

input:focus,
textarea:focus {
    border: 1px solid #2c8898;
}

textarea {
    width: 100%;
}

.button,
button,
input[type='submit'],
input[type='reset'],
input[type='button'] {
    display: inline-block;
    padding: 5px 10px;
    text-align: center;
    text-decoration: none;
    white-space: nowrap;
    background-color: #2c8898;
    color: #f9f9f9;
    border-radius: 1px;
    border: 1px solid #2c8898;
    cursor: pointer;
    box-sizing: border-box;
}

.button[disabled],
button[disabled],
input[type='submit'][disabled],
input[type='reset'][disabled],
input[type='button'][disabled] {
    cursor: default;
    opacity: 0.5;
}

.button:focus,
.button:hover,
button:focus,
button:hover,
input[type='submit']:focus,
input[type='submit']:hover,
input[type='reset']:focus,
input[type='reset']:hover,
input[type='button']:focus,
input[type='button']:hover {
    background-color: #982c61;
    border-color: #982c61;
    color: #f9f9f9;
    outline: 0;
}

textarea,
select,
input[type] {
    color: #4a4a4a;
    padding: 6px 10px;
    /* The 6px vertically centers text on FF, ignored by Webkit */
    margin-bottom: 10px;
    background-color: #f1f1f1;
    border: 1px solid #f1f1f1;
    border-radius: 4px;
    box-shadow: none;
    box-sizing: border-box;
}

textarea:focus,
select:focus,
input[type]:focus {
    border: 1px solid #2c8898;
    outline: 0;
}

label,
legend,
fieldset {
    display: block;
    margin-bottom: 0.5rem;
    font-weight: 600;
}
```

### package.json

```json
{
    "name": "express",
    "bin": "index.js",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "scripts": {
        "start": "node index.js",
        "test": "echo \"Error: no test specified\" && exit 1"
    },
    "pkg": {
        "scripts": "build/**/*.js",
        "assets": [
            "views/index.html",
            "views/**/*",
            "views/lib/**/*"
        ],
        "targets": [
            "node12"
        ]
    },
    "keywords": [],
    "author": "",
    "license": "ISC",
    "dependencies": {
        "express": "^4.17.1"
    }
}
```

I added the `"views/index.html",` and `"views/lib/**/*"` to see if it would recognize it but nothing worked.

### index.js

```javascript
/*jshint strict:false */

(function() {
    'use strict';
    // this function is strict...
}());

const express = require('express');
const app = express();
const Server = require('http').Server;
const server = new Server(app);

server.listen(8080);

// __dirname is used here along with package.json.pkg.assets
// sepkg .e https://github.com/zeit/pkg#config and
// https://github.com/zeit/pkg#snapshot-filesystem
app.use('/', express.static(__dirname + '/views'));

app.get('/', function(req, res) {
    res.sendFile(__dirname + '/views/index.html');
});
```

I can't seem to find the problem though.
***Help needed please...!**
